name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  build-mac:
    name: Build macOS universal
    runs-on: macos-11
    steps:
      - name: download and extract
        run: |
          curl --output xerces-c-3.2.4.tar.gz https://dlcdn.apache.org/xerces/c/3/sources/xerces-c-3.2.4.tar.gz
          tar xf xerces-c-3.2.4.tar.gz
      - name: build
        run: |
          sudo xcode-select -s /Applications/Xcode_12.4.app
          cd xerces-c-3.2.4
          ./configure --disable-network --enable-transcoder-macosunicodeconverter --enable-xmlch-char16_t --enable-mutexmgr-standard CFLAGS="-arch x86_64 -arch arm64" CXXFLAGS="-arch x86_64 -arch arm64"
          make -j4
          make DESTDIR=`pwd`/dist install-strip
      - name: package
        run: |
          cd xerces-c-3.2.4/dist/usr/local
          rm -rf bin
          zip -r ../../xerces-c-3.2.4-maxos-11-universal.zip *
      - uses: actions/upload-artifact@v3
        with:
          name: xerces-c-3.2.4-maxos-11-universal.zip
          path: xerces-c-3.2.4/dist/xerces-c-3.2.4-maxos-11-universal.zip
          if-no-files-found: error

  build-linux:
    name: Build linux x64
    runs-on: ubuntu-20.04
    steps:
      - name: download and extract
        run: |
          curl --output xerces-c-3.2.4.tar.gz https://dlcdn.apache.org/xerces/c/3/sources/xerces-c-3.2.4.tar.gz
          tar xf xerces-c-3.2.4.tar.gz
      - name: build
        run: |
          cd xerces-c-3.2.4
          ./configure --disable-network --enable-transcoder-iconv --enable-xmlch-char16_t --enable-mutexmgr-standard
          make -j4
          make DESTDIR=`pwd`/dist install-strip
      - name: infos
        run: |
          ls -l xerces-c-3.2.4/dist/usr/local/lib/
          ldd xerces-c-3.2.4/dist/usr/local/lib/libxerces-c-3.2.so
      - name: package
        run: |
          cd xerces-c-3.2.4/dist/usr/local
          rm -rf bin
          zip -r ../../xerces-c-3.2.4-linux-x64.zip *
      - uses: actions/upload-artifact@v3
        with:
          name: xerces-c-3.2.4-linux-x64.zip
          path: xerces-c-3.2.4/dist/xerces-c-3.2.4-linux-x64.zip
          if-no-files-found: error
  build-msvc:
    name: Build windows msvc 2019 x64
    runs-on: windows-2019
    steps:
      - name: download and extract
        run: |
          curl --output xerces-c-3.2.4.tar.gz https://dlcdn.apache.org/xerces/c/3/sources/xerces-c-3.2.4.tar.gz
          tar xf xerces-c-3.2.4.tar.gz
      - name: build
        run: |
          cd xerces-c-3.2.4
          cmake -G "Visual Studio 16 2019" -Dnetwork:BOOL=OFF  -Dtranscoder=windows -Dxmlch-type=char16_t -Dmutex-manager=standard
          cmake --build . --config Release 
          cmake --build . --config Release --target install
      - name: package
        run: |
          Copy-Item "C:\Program Files (x86)\xerces-c\bin\xerces-c_3_2.dll" -Destination "C:\Program Files (x86)\xerces-c\lib"
          Remove-Item -LiteralPath "C:\Program Files (x86)\xerces-c\share" -Force -Recurse
          Remove-Item -LiteralPath "C:\Program Files (x86)\xerces-c\bin" -Force -Recurse
          C:\"Program Files"\7-Zip\7z.exe a xerces-c-3.2.4-windows-msvc-2019-x64.zip C:\"Program Files (x86)"\xerces-c\
      - uses: actions/upload-artifact@v3
        with:
          name: xerces-c-3.2.4-windows-msvc-2019-x64.zip
          path: xerces-c-3.2.4-windows-msvc-2019-x64.zip
          if-no-files-found: error
  build-mingw:
    name: Build windows mingw x64
    runs-on: windows-2019
    steps:
      - name: download and extract
        run: |
          curl --output xerces-c-3.2.4.tar.gz https://dlcdn.apache.org/xerces/c/3/sources/xerces-c-3.2.4.tar.gz
          tar xf xerces-c-3.2.4.tar.gz
      - name: build
        run: |
          cd xerces-c-3.2.4
          cmake -G "MinGW Makefiles" -Dnetwork:BOOL=OFF  -Dtranscoder=windows -Dxmlch-type=char16_t -Dmutex-manager=standard
          cmake --build . --config Release 
          cmake --build . --config Release --target install
      - name: package
        run: |
          Copy-Item "C:\Program Files (x86)\xerces-c\bin\libxerces-c.dll" -Destination "C:\Program Files (x86)\xerces-c\lib"
          Remove-Item -LiteralPath "C:\Program Files (x86)\xerces-c\share" -Force -Recurse
          Remove-Item -LiteralPath "C:\Program Files (x86)\xerces-c\bin" -Force -Recurse
          C:\"Program Files"\7-Zip\7z.exe a xerces-c-3.2.4-windows-mingw-x64.zip C:\"Program Files (x86)"\xerces-c\
      - uses: actions/upload-artifact@v3
        with:
          name: xerces-c-3.2.4-windows-mingw-x64.zip
          path: xerces-c-3.2.4-windows-mingw-x64.zip
          if-no-files-found: error

  release:
    name: Release
    needs: [build-mac, build-linux, build-msvc, build-mingw]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: xerces-c-3.2.4-maxos-11-universal.zip
      - uses: actions/download-artifact@v3
        with:
          name: xerces-c-3.2.4-linux-x64.zip
      - uses: actions/download-artifact@v3
        with:
          name: xerces-c-3.2.4-windows-msvc-2019-x64.zip
      - uses: actions/download-artifact@v3
        with:
          name: xerces-c-3.2.4-windows-mingw-x64.zip
      - uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          prerelease: true
          files: |
            xerces-c-3.2.4-maxos-11-universal.zip
            xerces-c-3.2.4-linux-x64.zip
            xerces-c-3.2.4-windows-msvc-2019-x64.zip
            xerces-c-3.2.4-windows-mingw-x64.zip
