name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  build-mac:
    name: Build macOS automake x64
    runs-on: macos-11
    steps:
      - name: download and extract
        run: |
          curl --output xerces-c-3.2.4.tar.gz https://dlcdn.apache.org/xerces/c/3/sources/xerces-c-3.2.4.tar.gz
          tar xf xerces-c-3.2.4.tar.gz
      - name: build
        run: |
          sudo xcode-select -s /Applications/Xcode_12.4.app
          cd xerces-c-3.2.4
          ./configure --disable-network --enable-transcoder-macosunicodeconverter --enable-xmlch-char16_t --enable-mutexmgr-standard CFLAGS="-arch x86_64 -arch arm64" CXXFLAGS="-arch x86_64 -arch arm64"
          make -j4
          make DESTDIR=`pwd`/dist install-strip
      - name: package
        run: |
          cd xerces-c-3.2.4/dist/usr/local
          zip -r ../../xerces-c-3.2.4-maxos-11.zip *
      - uses: actions/upload-artifact@v3
        with:
          name: xerces-c-3.2.4-maxos-11.zip
          path: xerces-c-3.2.4/dist/xerces-c-3.2.4-maxos-11.zip
          if-no-files-found: error

  build-linux:
    name: Build linux automake x64
    runs-on: ubuntu-20.04
    steps:
      - name: download and extract
        run: |
          curl --output xerces-c-3.2.4.tar.gz https://dlcdn.apache.org/xerces/c/3/sources/xerces-c-3.2.4.tar.gz
          tar xf xerces-c-3.2.4.tar.gz
      - name: build
        run: |
          cd xerces-c-3.2.4
          ./configure --disable-network --enable-transcoder-iconv --enable-xmlch-char16_t --enable-mutexmgr-standard
          make -j4
          make DESTDIR=`pwd`/dist install-strip
      - name: infos
        run: |
          ls -l xerces-c-3.2.4/dist/usr/local/lib/
          ldd xerces-c-3.2.4/dist/usr/local/lib/libxerces-c-3.2.so
      - name: package
        run: |
          cd xerces-c-3.2.4/dist/usr/local
          zip -r ../../xerces-c-3.2.4-linux-x64.zip *
      - uses: actions/upload-artifact@v3
        with:
          name: xerces-c-3.2.4-linux-x64.zip
          path: xerces-c-3.2.4/dist/xerces-c-3.2.4-linux-x64.zip
          if-no-files-found: error
  build-linux-cmake:
    name: Build linux x64 with cmake
    runs-on: ubuntu-20.04
    steps:
      - name: download and extract
        run: |
          curl --output xerces-c-3.2.4.tar.gz https://dlcdn.apache.org/xerces/c/3/sources/xerces-c-3.2.4.tar.gz
          tar xf xerces-c-3.2.4.tar.gz
      - name: build
        run: |
          cd xerces-c-3.2.4
          cmake -G "Unix Makefiles" -Dnetwork:BOOL=OFF  -Dtranscoder=iconv -Dxmlch-type=char16_t -Dmutex-manager=standard -DCMAKE_INSTALL_PREFIX=/opt/xerces-c
          cmake --build . --config Release
          sudo cmake --build . --config Release --target install
      - name: infos
        run: |
          ls -l /opt/xerces-c/lib
          ldd /opt/xerces-c/lib/libxerces-c-3.2.so
      - name: package
        run: |
          zip -r xerces-c-3.2.4-linux-cmake-x64.zip /opt/xerces-c/
      - uses: actions/upload-artifact@v3
        with:
          name: xerces-c-3.2.4-linux-cmake-x64.zip
          path: xerces-c-3.2.4-linux-cmake-x64.zip
          if-no-files-found: error
  build-msvc:
    name: Build Windows msvc 2019 x64
    runs-on: windows-2019
    steps:
      - name: download and extract
        run: |
          curl --output xerces-c-3.2.4.tar.gz https://dlcdn.apache.org/xerces/c/3/sources/xerces-c-3.2.4.tar.gz
          tar xf xerces-c-3.2.4.tar.gz
      - name: build
        run: |
          cd xerces-c-3.2.4
          cmake -G "Visual Studio 16 2019" -Dnetwork:BOOL=OFF  -Dtranscoder=windows -Dxmlch-type=char16_t -Dmutex-manager=standard
          cmake --build . --config Release 
          cmake --build . --config Release --target install
      - name: package
        run: |
          C:\"Program Files"\7-Zip\7z.exe a xerces-c-3.2.4-windows-msvc-2019-x64.zip C:\"Program Files (x86)"\xerces-c\
      - uses: actions/upload-artifact@v3
        with:
          name: xerces-c-3.2.4-windows-msvc-2019-x64.zip
          path: xerces-c-3.2.4-windows-msvc-2019-x64.zip
          if-no-files-found: error
  build-mingw:
    name: Build Windows mingw x64
    runs-on: windows-2019
    steps:
      - name: download and extract
        run: |
          curl --output xerces-c-3.2.4.tar.gz https://dlcdn.apache.org/xerces/c/3/sources/xerces-c-3.2.4.tar.gz
          tar xf xerces-c-3.2.4.tar.gz
      - name: build
        run: |
          cd xerces-c-3.2.4
          cmake -G "MinGW Makefiles" -Dnetwork:BOOL=OFF  -Dtranscoder=windows -Dxmlch-type=char16_t -Dmutex-manager=standard
          cmake --build . --config Release 
          cmake --build . --config Release --target install
      - name: package
        run: |
          C:\"Program Files"\7-Zip\7z.exe a xerces-c-3.2.4-windows-mingw-x64.zip C:\"Program Files (x86)"\xerces-c\
      - uses: actions/upload-artifact@v3
        with:
          name: xerces-c-3.2.4-windows-mingw-x64.zip
          path: xerces-c-3.2.4-windows-mingw-x64.zip
          if-no-files-found: error
